### ISSUE TITLE
Styles not loading on .onion site post-branding update

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#689]
![Screenshot 2024-10-11 at 10 17 05 AM](https://github.com/user-attachments/assets/5749eb66-e2a7-41a9-a0ba-9aee11674b55)

**Comment by brassy-endomorph** [comment]
Just noting that I got this on Firefox 115 when testing the branding update and it mysteriously resolved itself for no apparent reason.

**Comment by rmlibre** [comment]
I believe this may be due to prior versions of **Tor Browser (12.x.x)** being based on **Firefox ESR 102.x.x**. Since October of 2023, the switch was made to **Tor Browser 13.x.x** based on **Firefox ESR 115.x.x**. The ``oklch`` color format began official support in **Firefox ESR 113.x.x** in May 2023.

**[Tor Browser Changelog](https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/raw/main/projects/browser/Bundle-Data/Docs-TBB/ChangeLog.txt)**

**[OKLCH Browser Support](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch)**
![oklch_browser_support_0000](https://github.com/user-attachments/assets/c35314c6-f5f2-4a8a-8a33-dd7d53ad3978)
