### ISSUE TITLE
Perfectly good password is rejected

### ISSUE THREAD

**Issue by micahflee** [scidsg/hushline#713]
**Describe the bug**
I tried to update my password to `run-pointy-comforts-HOLLING` fails with the flash error message:

> ⛔️ Invalid form data. Please try again.

**To Reproduce**
Try changing your password to `run-pointy-comforts-HOLLING`.

**Expected behavior**
Any passwords like this should work.

**Comment by brassy-endomorph** [comment]
It's not a bug. It's following the rules for password, and we can see that if we change the `/change-password` endpoint to have this flash message:

```python
flash("⛔️ Invalid form data. Please try again." + str(change_password_form.errors), "error")
```

It says:

```
⛔️ Invalid form data. Please try again.{'new_password': ['⛔️ Password must include uppercase, lowercase, digit, and a special character.']}
```

This isn't rendered on the `/settings/` page (authentication tab) because the errors are lost once we redirect.

Forms should always submit to the endpoint they're currently on to prevent this class of error.
