### ISSUE TITLE
Allow admin to set the homepage path

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#808]
An admin should be able to set the homepage of their app. Currently we default to `/directory` but some instance owners want visitors to always land on a specific account.

**Acceptance Criteria**
1. Only pages on the same domain are valid. For example, an admin cannot direct to any third party site.
2. From `Settings > Admin` a user may toggle on or off the user directory.
3. The default home page for instances with disabled directories should direct to the login form.
4. An admin can define a custom page inside of their instance to which users should redirect.

**Mockup**
![Group 334](https://github.com/user-attachments/assets/95ea887c-7e0c-45e1-be48-187c6972c0db)

**Comment by brassy-endomorph** [comment]
First:

> The default home page for instances with disabled directories should direct to the login form.

Is that a specific requirement or is that just a thing we think we should do for that edge case?

This might be a slightly improved simplification:

1. Default is someone lands on `/directory`
2. If a new landing page is defined, the directory can be disabled
3. For now, you can only select a user to be the new landing page, not any landing page
4. On error if the user doesn't exist, redirect to `/directory` if it is enabled. Or 500 if it's disabled.

**Comment by glenn-sorrentino** [comment]
> 2. If a new landing page is defined, the directory can be disabled

I don't love that the toggle is only active if a new homepage has been defined. It's clean enough for code, but not a good UX. It'd make us have to add instructions about why the behavior is that way, and is too much thinking and work just to turn off the directory.

> 3. For now, you can only select a user to be the new landing page, not any landing page

Why only users? An admin might want to direct to the login or register page.

> 4. On error if the user doesn't exist, redirect to `/directory` if it is enabled. Or 500 if it's disabled.

This is why we should have a default fallback page. The app should never 500 just because the user hasn't done something we want them to do.

**Comment by brassy-endomorph** [comment]
> Why only users? An admin might want to direct to the login or register page.

Why would the want that? If the site is at `https://tips.example.com`, then they would just link directly to the index page every time. If we support mounting to a path (`e.g., https://example.com/tips/`) then again, they'd just link to that. I cannot think of any websites that auto-redirect from `/` to a login that _don't_ require a login somewhere else. This is also much more complicated as we'd have to have logic to prevent infinite redirects, validation of URLs, etc. It is far far easier to code and reason about if we start by just saying "only users."

> Why only users? An admin might want to direct to the login or register page.

This should then be the directory. Otherwise if the directory is disabled and the default page is a generic "homepage" then a user wouldn't ever be able to do anything and is "stuck."

I'm not sure why we want to disable the directory at all, tbh. If we do, it at the very least should redirect to the index or something else.
